# Generated by Django 3.1 on 2020-08-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
