# Generated by Django 3.1 on 2020-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0002_myuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='homepage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
